#!/bin/bash

# Stop script if there is an error
set -e

# Setup project
echo "Setting up project locally..."
pnpm install

# Start project
echo "Starting project..."
pnpm start &

# Optional: Wait for the project to start (could be useful in some cases)
# sleep 5

echo "Project is running..."